name: Sync Upstream and HTTPS Push to Gitea.com

on:
  schedule:
    - cron: '0 8 * * *' 
  workflow_dispatch:
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  sync-and-mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Sync Fork with Upstream
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh repo sync ${{ github.repository }} --force

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Gitea via Token
        run: |
          # 定义变量以便修改
          # 注意：把下面的地址换成你 Gitea 的实际地址（不带 http://，只写域名或 IP）
          GITEA_HOST="gitea.com"
          GITEA_USER="weweuk"
          GITEA_REPO="ios_rule_script"
          
          # 使用 Token 构建带权限的 HTTPS 地址
          # 格式为：https://用户名:Token@域名/用户名/仓库名.git
          REMOTE_URL="https://${GITEA_USER}:${{ secrets.GITEA_COM_TOKEN }}@${GITEA_HOST}/${GITEA_USER}/${GITEA_REPO}.git"
          
          # 强制推送
          git push "$REMOTE_URL" --all --force
          git push "$REMOTE_URL" --tags --force
